# Generated by Django 5.0.1 on 2024-02-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
